# Bettermix Plugin config.yml
# 存放于 plugins/Bettermix/config.yml

tuic_port: ""
hy2_port: ""
reality_port: ""
sni: "www.bing.com"

# komari-agent 配置
komari_agent_enabled: true
komari_agent_name: "bettermix"
komari_agent_ver: "1.0.1"
komari_agent_endpoint: ""        # komari 服务器地址（填了才启动）
komari_agent_key: ""             # 自动发现密钥（填了才启动）

# Telegram 推送（选填，留空则不推送）
tg_bot_token: ""                 # Telegram Bot Token
tg_chat_id: ""                   # Telegram 聊天/频道 ID